CREATE TABLE CON_T_ADMIN (
    id VARCHAR2(32) Primary key,
    pw VARCHAR2(32) NOT NULL,
    name VARCHAR2(32) NOT NULL,
    tel VARCHAR(8),
    position VARCHAR2(32),
    role VARCHAR2(32),
    status VARCHAR2(32),
    emp_date DATE DEFAULT SYSDATE
);


CREATE SEQUENCE SEQ_CON_T_ADMIN_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;