CREATE TABLE CON_T_ADMIN (
    id VARCHAR2(32) Primary key,
    pw VARCHAR2(32) NOT NULL,
    name VARCHAR2(32) NOT NULL,
    tel VARCHAR(8),
    position VARCHAR2(32),
    role VARCHAR2(32),
    status VARCHAR2(32),
    emp_date DATE DEFAULT SYSDATE
);


CREATE SEQUENCE SEQ_CON_T_ADMIN_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;


CREATE TABLE CON_T_USER (
    id VARCHAR2(20) Primary key,
    pw VARCHAR2(100) NOT NULL,
    name VARCHAR2(30) NOT NULL,
    tel VARCHAR(15),
    mail VARCHAR2(100),
    adress VARCHAR2(200),
    join_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20),
    point NUMBER(10)
);


CREATE SEQUENCE SEQ_CON_T_USER_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;