-- 분류체계 코드 테이블 
CREATE TABLE TOUR_CLASSIFICATION_SYSTEM_CODE (
	RNUM			NUMBER PRIMARY KEY,
    LCLS_SYSTM1_CD  VARCHAR2(10) NOT NULL,   -- 분류체계 대분류 코드 (예: 'AC' 숙박)
    LCLS_SYSTM1_NM  VARCHAR2(100) NOT NULL,  -- 분류체계 대분류명
    LCLS_SYSTM2_CD  VARCHAR2(10),            -- 분류체계 중분류 코드 (예: 'AC01' 호텔)
    LCLS_SYSTM2_NM  VARCHAR2(100),           -- 분류체계 중분류명
    LCLS_SYSTM3_CD  VARCHAR2(10),            -- 분류체계 소분류 코드 (예: 'AC010100' 호텔)
    LCLS_SYSTM3_NM  VARCHAR2(100),           -- 분류체계 소분류명
    CREATED_TIME    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    MODIFIED_TIME   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
COMMENT ON TABLE TOUR_CLASSIFICATION_SYSTEM_CODE IS '분류체계 코드 정보 테이블';
COMMENT ON COLUMN TOUR_CLASSIFICATION_SYSTEM_CODE.RNUM IS '일련번호';
COMMENT ON COLUMN TOUR_CLASSIFICATION_SYSTEM_CODE.LCLS_SYSTM1_CD IS '분류체계 대분류 코드';
COMMENT ON COLUMN TOUR_CLASSIFICATION_SYSTEM_CODE.LCLS_SYSTM1_NM IS '분류체계 대분류명';
COMMENT ON COLUMN TOUR_CLASSIFICATION_SYSTEM_CODE.LCLS_SYSTM2_CD IS '분류체계 중분류 코드';
COMMENT ON COLUMN TOUR_CLASSIFICATION_SYSTEM_CODE.LCLS_SYSTM2_NM IS '분류체계 중분류명';
COMMENT ON COLUMN TOUR_CLASSIFICATION_SYSTEM_CODE.LCLS_SYSTM3_CD IS '분류체계 소분류 코드';
COMMENT ON COLUMN TOUR_CLASSIFICATION_SYSTEM_CODE.LCLS_SYSTM3_NM IS '분류체계 소분류명';
COMMENT ON COLUMN TOUR_CLASSIFICATION_SYSTEM_CODE.CREATED_TIME IS '레코드 생성 시간';
COMMENT ON COLUMN TOUR_CLASSIFICATION_SYSTEM_CODE.MODIFIED_TIME IS '레코드 최종 수정 시간';

select * from ;


-- 관광 목적지 정보 테이블 
CREATE TABLE TOUR_DESTINATION (
    CONTENT_ID          NUMBER PRIMARY KEY,
    CONTENT_TYPE_ID     NUMBER NOT NULL,
    TITLE               VARCHAR2(500) NOT NULL,
    ADDR1               VARCHAR2(1000),
    ADDR2               VARCHAR2(1000),
    ZIPCODE             VARCHAR2(10),
    AREA_CODE           VARCHAR2(10),
    SIGUNGU_CODE        VARCHAR2(10),
    CAT1                VARCHAR2(10),
    CAT2                VARCHAR2(10),
    CAT3                VARCHAR2(10),
    MAPX                NUMBER(15, 10),
    MAPY                NUMBER(15, 10),
    MLEVEL				NUMBER(3),
    TEL                 VARCHAR2(100),    
    FIRST_IMAGE         VARCHAR2(2000),
    FIRST_IMAGE2        VARCHAR2(2000),
    CPYRHT_DIV_CD       VARCHAR2(10),
    LDONG_REGN_CD       VARCHAR2(5),    -- 법정동 시도 코드 
    LDONG_SIGNGU_CD     VARCHAR2(5),    -- 법정동 시군구 코드 
    LCLS_SYSTM1      VARCHAR2(10),   -- 분류체계 대분류 코드 
    LCLS_SYSTM2     VARCHAR2(10),   -- 분류체계 중분류 코드 
    LCLS_SYSTM3     VARCHAR2(10),   -- 분류체계 소분류 코드
    CREATED_TIME    VARCHAR2(40), -- API 응답의 createdtime (YYYYMMDDHHMMSS)
    MODIFIED_TIME  VARCHAR2(40) -- API 응답의 modifiedtime (YYYYMMDDHHMMSS)
);


COMMENT ON TABLE TOUR_DESTINATION IS '관광 목적지 정보 테이블';
COMMENT ON COLUMN TOUR_DESTINATION.CONTENT_ID IS '콘텐츠 ID';
COMMENT ON COLUMN TOUR_DESTINATION.CONTENT_TYPE_ID IS '관광타입 ID';
COMMENT ON COLUMN TOUR_DESTINATION.TITLE IS '콘텐츠 제목';
COMMENT ON COLUMN TOUR_DESTINATION.ADDR1 IS '주소';
COMMENT ON COLUMN TOUR_DESTINATION.ADDR2 IS '상세주소';
COMMENT ON COLUMN TOUR_DESTINATION.ZIPCODE IS '우편번호';
COMMENT ON COLUMN TOUR_DESTINATION.AREA_CODE IS '지역코드';
COMMENT ON COLUMN TOUR_DESTINATION.SIGUNGU_CODE IS '시군구코드';
COMMENT ON COLUMN TOUR_DESTINATION.CAT1 IS '대분류 코드';
COMMENT ON COLUMN TOUR_DESTINATION.CAT2 IS '중분류 코드';
COMMENT ON COLUMN TOUR_DESTINATION.CAT3 IS '소분류 코드';
COMMENT ON COLUMN TOUR_DESTINATION.MAPX IS 'GPS X좌표 (WGS84 경도 좌표)';
COMMENT ON COLUMN TOUR_DESTINATION.MAPY IS 'GPS Y좌표 (WGS84 위도 좌표)';
COMMENT ON COLUMN TOUR_DESTINATION.MLEVEL IS 'Map Level';
COMMENT ON COLUMN TOUR_DESTINATION.TEL IS '전화번호';
COMMENT ON COLUMN TOUR_DESTINATION.CREATED_TIME IS 'API 응답의 콘텐츠 최초 등록일';
COMMENT ON COLUMN TOUR_DESTINATION.MODIFIED_TIME IS 'API 응답의 콘텐츠 수정일';
COMMENT ON COLUMN TOUR_DESTINATION.FIRST_IMAGE IS '대표이미지(원본) URL';
COMMENT ON COLUMN TOUR_DESTINATION.FIRST_IMAGE2 IS '대표이미지(썸네일) URL';
COMMENT ON COLUMN TOUR_DESTINATION.CPYRHT_DIV_CD IS '저작권 유형';
COMMENT ON COLUMN TOUR_DESTINATION.LDONG_REGN_CD IS '법정동 시도 코드';
COMMENT ON COLUMN TOUR_DESTINATION.LDONG_SIGNGU_CD IS '법정동 시군구 코드';
COMMENT ON COLUMN TOUR_DESTINATION.LCLS_SYSTM1 IS '분류체계 대분류 코드';
COMMENT ON COLUMN TOUR_DESTINATION.LCLS_SYSTM2 IS '분류체계 중분류 코드';
COMMENT ON COLUMN TOUR_DESTINATION.LCLS_SYSTM3 IS '분류체계 소분류 코드';
COMMENT ON COLUMN TOUR_DESTINATION.CREATED_TIME IS '레코드 생성 시간';
COMMENT ON COLUMN TOUR_DESTINATION.MODIFIED_TIME IS '레코드 최종 수정 시간';


--수정시간 자동으로 업데이트 하는 트리거
CREATE OR REPLACE TRIGGER TRG_TOUR_AREA_CODE_MOD
BEFORE UPDATE ON TOUR_AREA_CODE
FOR EACH ROW
BEGIN
    :NEW.LAST_UPDATED_DATE := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_TOUR_CLASSIFICATION_SYSTEM_CODE_MOD
BEFORE UPDATE ON TOUR_CLASSIFICATION_SYSTEM_CODE
FOR EACH ROW
BEGIN
    :NEW.MODIFIED_TIME := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_TOUR_DESTINATION_MOD
BEFORE UPDATE ON TOUR_DESTINATION
FOR EACH ROW
BEGIN
    :NEW.MODIFIED_TIME := SYSTIMESTAMP;
END;
/



--------------------------------------------소개정보 조회


CREATE TABLE TOUR_DETAIL_INTRO_ATTRACTION(
	CONTENT_ID          NUMBER PRIMARY KEY,
    CONTENT_TYPE_ID     NUMBER NOT NULL,
    ACCOM_COUNT			VARCHAR2(5),
    CHK_BABY_CARRIAGE	VARCHAR2(10),
    CHK_CREDIT_CARD		VARCHAR2(10),
    CHK_PET				VARCHAR2(10),
    EXP_AGE_RANGE		VARCHAR2(100),
    EXP_GUIDE			VARCHAR2(100),
    HERITAGE1			VARCHAR2(10),
    HERITAGE2			VARCHAR2(10),
    HERITAGE3			VARCHAR2(10),
    INFO_CENTER			VARCHAR2(1000),
    OPEN_DATE			VARCHAR2(1000),
	PARKING				VARCHAR2(1000),
	REST_DATE			VARCHAR2(1000),
	USE_SEASON			VARCHAR2(1000),
	USE_TIME			VARCHAR2(1000),
	CREATED_TIME    	VARCHAR2(40), 
    MODIFIED_TIME  		VARCHAR2(40) 
);

COMMENT ON TABLE TOUR_DETAIL_INTRO_ATTRACTION IS '관광지(contentTypeId=12) 소개 정보 테이블';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.CONTENT_ID IS '콘텐츠 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.CONTENT_TYPE_ID IS '관광타입 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.ACCOM_COUNT IS '수용인원';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.CHK_BABY_CARRIAGE IS '유모차 대여 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.CHK_CREDIT_CARD IS '신용카드 가능 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.CHK_PET IS '애완동물 동반 가능 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.EXP_AGE_RANGE IS '체험가능 연령';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.EXP_GUIDE IS '체험안내';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.HERITAGE1 IS '세계 문화유산 유무';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.HERITAGE2 IS '세계 자연유산 유무';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.HERITAGE3 IS '세계 기록유산 유무';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.INFO_CENTER IS '문의 및 안내';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.OPEN_DATE IS '개장일';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.PARKING IS '주차시설';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.REST_DATE IS '쉬는 날';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.USE_SEASON IS '이용시기';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.USE_TIME IS '이용시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.CREATED_TIME IS '레코드 생성 시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_ATTRACTION.MODIFIED_TIME IS '레코드 최종 수정 시간';


CREATE TABLE TOUR_DETAIL_INTRO_CULTURAL_FACILITY(
	CONTENT_ID          NUMBER PRIMARY KEY,
    CONTENT_TYPE_ID     NUMBER NOT NULL,
    ACCOM_COUNT			VARCHAR2(5),
    CHK_BABY_CARRIAGE		VARCHAR2(10),
    CHK_CREDIT_CARD		VARCHAR2(10),
    CHK_PET				VARCHAR2(10),
    DISCOUNT_INFO		VARCHAR2(1000),
    INFO_CENTER_CULTURE	VARCHAR2(100),
    PARKING_CULTURE		VARCHAR2(1000),
    PARKING_FEE			VARCHAR2(100),
    REST_DATE_CULTURE		VARCHAR2(1000),
    USE_FEE				VARCHAR2(1000),
    USE_TIME_CULTURE		VARCHAR2(1000),
	SCALE				VARCHAR2(1000),
	SPEND_TIME			VARCHAR2(1000),
	CREATED_TIME    	VARCHAR2(40), 
    MODIFIED_TIME  		VARCHAR2(40) 
);

COMMENT ON TABLE TOUR_DETAIL_INTRO_CULTURAL_FACILITY IS '문화시설(contentTypeId=14) 소개 정보 테이블';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.CONTENT_ID IS '콘텐츠 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.CONTENT_TYPE_ID IS '관광타입 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.ACCOM_COUNT IS '수용인원';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.CHK_BABY_CARRIAGE IS '유모차 대여 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.CHK_CREDIT_CARD IS '신용카드 가능 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.CHK_PET IS '애완동물 동반 가능 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.DISCOUNT_INFO IS '할인정보';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.INFO_CENTER_CULTURE IS '문의 및 안내';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.PARKING_CULTURE IS '주차시설';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.PARKING_FEE IS '주차요금';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.REST_DATE_CULTURE IS '쉬는 날';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.USE_FEE IS '이용요금';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.USE_TIME_CULTURE IS '이용시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.SCALE IS '규모';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.SPEND_TIME IS '관람 소요시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.CREATED_TIME IS '레코드 생성 시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_CULTURAL_FACILITY.MODIFIED_TIME IS '레코드 최종 수정 시간';

CREATE TABLE TOUR_DETAIL_INTRO_FESTIVAL(
	CONTENT_ID          NUMBER PRIMARY KEY,
    CONTENT_TYPE_ID     NUMBER NOT NULL,
  	AGE_LIMIT  			VARCHAR2(1000),
    BOOKING_PLACE		VARCHAR2(1000),
    DISCOUNT_INFO_FESTIVAL VARCHAR2(1000),
    EVENT_END_DATE		VARCHAR2(100),
    EVENT_HOMEPAGE		VARCHAR2(1000),
    EVENT_PLACE			VARCHAR2(1000),
    EVENT_START_DATE	VARCHAR2(100),
    FESTIVAL_GRADE		VARCHAR2(100),
    PLACE_INFO			VARCHAR2(1000),
    PLAY_TIME			VARCHAR2(1000),
    PROGRAM				VARCHAR2(1000),
    SPEND_TIME_FESTIVAL	VARCHAR2(100),
    SPONSOR1			VARCHAR2(1000),
    SPONSOR1_TEL		VARCHAR2(100),
    SPONSOR2			VARCHAR2(1000),
    SPONSOR2_TEL		VARCHAR2(100),
    SUB_EVENT			VARCHAR2(1000),
    USE_TIME_FESTIVAL	VARCHAR2(100),
    CREATED_TIME    	VARCHAR2(40), 
    MODIFIED_TIME  		VARCHAR2(40)
);

COMMENT ON TABLE TOUR_DETAIL_INTRO_FESTIVAL IS '행사/축제/공연(contentTypeId=15) 소개 정보 테이블';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.CONTENT_ID IS '콘텐츠 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.CONTENT_TYPE_ID IS '관광타입 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.AGE_LIMIT IS '관람 가능연령';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.BOOKING_PLACE IS '예매처';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.DISCOUNT_INFO_FESTIVAL IS '할인정보';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.EVENT_END_DATE IS '행사 종료일';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.EVENT_HOMEPAGE IS '행사 홈페이지';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.EVENT_PLACE IS '행사 장소';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.EVENT_START_DATE IS '행사 시작일';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.FESTIVAL_GRADE IS '축제등급';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.PLACE_INFO IS '행사장 위치안내';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.PLAY_TIME IS '공연시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.PROGRAM IS '행사 프로그램';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.SPEND_TIME_FESTIVAL IS '관람 소요시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.SPONSOR1 IS '주최자 정보';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.SPONSOR1_TEL IS '주최자 연락처';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.SPONSOR2 IS '주관사 정보';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.SPONSOR2_TEL IS '주관사 연락처';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.SUB_EVENT IS '부대행사';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.USE_TIME_FESTIVAL IS '이용시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.CREATED_TIME IS '레코드 생성 시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FESTIVAL.MODIFIED_TIME IS '레코드 최종 수정 시간';



CREATE TABLE TOUR_DETAIL_INTRO_LEPORTS(
	CONTENT_ID          		NUMBER PRIMARY KEY,
    CONTENT_TYPE_ID     		NUMBER NOT NULL,
 	ACCOM_COUNT_LEPORTS   		VARCHAR2(100),
    CHK_BABY_CARRIAGE_LEPORTS	VARCHAR2(100),
    CHK_CREDIT_CARD_LEPORTS		VARCHAR2(100),
    CHK_PET_LEPORTS				VARCHAR2(100),
    EXP_AGE_RANGE_LEPORTS		VARCHAR2(100),
    INFO_CENTER_LEPORTS			VARCHAR2(100),
    OPEN_PERIOD					VARCHAR2(1000),
    PARKING_FEE_LEPORTS			VARCHAR2(100),
    PARKING_LEPORTS				VARCHAR2(100),
    RESERVATION					VARCHAR2(100),
    REST_DATE_LEPORTS			VARCHAR2(100),
    SCALE_LEPORTS				VARCHAR2(100),
    USE_FEE_LEPORTS				VARCHAR2(100),
    USE_TIME_LEPORTS			VARCHAR2(100),
	CREATED_TIME    			VARCHAR2(40), 
    MODIFIED_TIME  				VARCHAR2(40) 
)    

COMMENT ON TABLE TOUR_DETAIL_INTRO_LEPORTS IS '레포츠(contentTypeId=28) 소개 정보 테이블';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.CONTENT_ID IS '콘텐츠 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.CONTENT_TYPE_ID IS '관광타입 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.ACCOM_COUNT_LEPORTS IS '수용인원';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.CHK_BABY_CARRIAGE_LEPORTS IS '유모차 대여 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.CHK_CREDIT_CARD_LEPORTS IS '신용카드 가능 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.CHK_PET_LEPORTS IS '애완동물 동반 가능 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.EXP_AGE_RANGE_LEPORTS IS '체험 가능연령';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.INFO_CENTER_LEPORTS IS '문의 및 안내';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.OPEN_PERIOD IS '개장기간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.PARKING_FEE_LEPORTS IS '주차요금';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.PARKING_LEPORTS IS '주차시설';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.RESERVATION IS '예약안내';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.REST_DATE_LEPORTS IS '쉬는 날';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.SCALE_LEPORTS IS '규모';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.USE_FEE_LEPORTS IS '입장료';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.USE_TIME_LEPORTS IS '이용시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.CREATED_TIME IS '레코드 생성 시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LEPORTS.MODIFIED_TIME IS '레코드 최종 수정 시간';


CREATE TABLE TOUR_DETAIL_INTRO_LODGING(
	CONTENT_ID          		NUMBER PRIMARY KEY,
    CONTENT_TYPE_ID     		NUMBER NOT NULL,
    ACCOM_COUNT_LODGING			VARCHAR2(100),
    CHECKIN_TIME				VARCHAR2(100),
    CHECKOUT_TIME				VARCHAR2(100),
    CHK_COOKING					VARCHAR2(100),
    FOOD_PLACE					VARCHAR2(100),	
    INFO_CENTER_LODGING			VARCHAR2(100),
    PARKING_LODGING				VARCHAR2(100),
    PICKUP						VARCHAR2(10),
    ROOM_COUNT					VARCHAR2(20),
    RESERVATION_LODGING			VARCHAR2(100),
    RESERVATION_URL				VARCHAR2(1000),
    ROOM_TYPE					VARCHAR2(100),
    SCALE_LODGING				VARCHAR2(100),
    SUB_FACILITY				VARCHAR2(1000),
    BARBECUE					VARCHAR2(10),
    BEAUTY						VARCHAR2(10),
    BEVERAGE					VARCHAR2(10),
    BICYCLE						VARCHAR2(10),
    CAMPFIRE					VARCHAR2(10),
    FITNESS						VARCHAR2(10),
    KARAOKE						VARCHAR2(10),
    PUBLIC_BATH					VARCHAR2(10),
    PUBLIC_PC					VARCHAR2(10),
    SAUNA						VARCHAR2(10),
    SEMINAR						VARCHAR2(10),	
    SPORTS						VARCHAR2(10),
    REFUND_REGULATION			VARCHAR2(1000),
	CREATED_TIME    			VARCHAR2(40), 
    MODIFIED_TIME  				VARCHAR2(40) 
);

COMMENT ON TABLE TOUR_DETAIL_INTRO_LODGING IS '숙박(contentTypeId=32) 소개 정보 테이블';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.CONTENT_ID IS '콘텐츠 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.CONTENT_TYPE_ID IS '관광타입 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.ACCOM_COUNT_LODGING IS '수용 가능인원';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.CHECKIN_TIME IS '입실 시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.CHECKOUT_TIME IS '퇴실 시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.CHK_COOKING IS '객실내 취사 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.FOOD_PLACE IS '식음료장';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.INFO_CENTER_LODGING IS '문의 및 안내';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.PARKING_LODGING IS '주차시설';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.PICKUP IS '픽업 서비스';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.ROOM_COUNT IS '객실수';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.RESERVATION_LODGING IS '예약안내';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.RESERVATION_URL IS '예약안내 홈페이지';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.ROOM_TYPE IS '객실유형';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.SCALE_LODGING IS '규모';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.SUB_FACILITY IS '부대시설 (기타)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.BARBECUE IS '바비큐장 여부 (부대시설)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.BEAUTY IS '뷰티시설 정보 (부대시설)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.BEVERAGE IS '식음료장 여부 (부대시설)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.BICYCLE IS '자전거 대여 여부 (부대시설)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.CAMPFIRE IS '캠프파이어 여부 (부대시설)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.FITNESS IS '휘트니스 센터 여부 (부대시설)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.KARAOKE IS '노래방 여부 (부대시설)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.PUBLIC_BATH IS '공용 샤워실 여부 (부대시설)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.PUBLIC_PC IS '공용 PC실 여부 (부대시설)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.SAUNA IS '사우나실 여부 (부대시설)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.SEMINAR IS '세미나실 여부 (부대시설)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.SPORTS IS '스포츠 시설 여부 (부대시설)';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.REFUND_REGULATION IS '환불규정';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.CREATED_TIME IS '레코드 생성 시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_LODGING.MODIFIED_TIME IS '레코드 최종 수정 시간';


CREATE TABLE TOUR_DETAIL_INTRO_SHOPPING(
	CONTENT_ID          			NUMBER PRIMARY KEY,
    CONTENT_TYPE_ID     			NUMBER NOT NULL,
  	CHK_BABY_CARRIAGE_SHOPPING		VARCHAR2(10),
  	CHK_CREDIT_CARD_SHOPPING		VARCHAR2(10),
  	CHK_PET_SHOPPING				VARCHAR2(10),
  	CULTURE_CENTER					VARCHAR2(100),
  	FAIR_DAY						VARCHAR2(100),
  	INFO_CENTER_SHOPPING			VARCHAR2(1000),
    OPEN_DATE_SHOPPING				VARCHAR2(100),
    OPEN_TIME						VARCHAR2(100),
    PARKING_SHOPPING				VARCHAR2(10),
    REST_DATE_SHOPPING				VARCHAR2(100),
    REST_ROOM						VARCHAR2(10),
    SALE_ITEM						VARCHAR2(100),
    SALE_ITEM_COST					VARCHAR2(100),
    SCALE_SHOPPING					VARCHAR2(100),
    SHOP_GUIDE						VARCHAR2(1000),
	CREATED_TIME    				VARCHAR2(40), 
    MODIFIED_TIME  					VARCHAR2(40) 
);    

COMMENT ON TABLE TOUR_DETAIL_INTRO_SHOPPING IS '쇼핑(contentTypeId=38) 소개 정보 테이블';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.CONTENT_ID IS '콘텐츠 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.CONTENT_TYPE_ID IS '관광타입 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.CHK_BABY_CARRIAGE_SHOPPING IS '유모차 대여 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.CHK_CREDIT_CARD_SHOPPING IS '신용카드 가능 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.CHK_PET_SHOPPING IS '애완동물 동반 가능 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.CULTURE_CENTER IS '문화센터 바로가기';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.FAIR_DAY IS '장 서는 날';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.INFO_CENTER_SHOPPING IS '문의 및 안내';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.OPEN_DATE_SHOPPING IS '개장일';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.OPEN_TIME IS '영업시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.PARKING_SHOPPING IS '주차시설';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.REST_DATE_SHOPPING IS '쉬는 날';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.REST_ROOM IS '화장실 설명';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.SALE_ITEM IS '판매 품목';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.SALE_ITEM_COST IS '판매 품목별 가격';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.SCALE_SHOPPING IS '규모';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.SHOP_GUIDE IS '매장안내';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.CREATED_TIME IS '레코드 생성 시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_SHOPPING.MODIFIED_TIME IS '레코드 최종 수정 시간';


CREATE TABLE TOUR_DETAIL_INTRO_FOOD(
	CONTENT_ID          			NUMBER PRIMARY KEY,
    CONTENT_TYPE_ID     			NUMBER NOT NULL,
    CHK_CREDIT_CARD_FOOD			VARCHAR2(10),
    DISCOUNT_INFO_FOOD				VARCHAR2(100),
    FIRST_MENU						VARCHAR2(100),
    INFO_CENTER_FOOD				VARCHAR2(100),
    KIDS_FACILITY					VARCHAR2(10),
    OPEN_DATE_FOOD					VARCHAR2(100),
    OPEN_TIME_FOOD					VARCHAR2(100),
    PACKING							VARCHAR2(10),
    PARKING_FOOD					VARCHAR2(10),	
    RESERVATION_FOOD				VARCHAR2(100),
    REST_DATE_FOOD					VARCHAR2(100),
    SCALE_FOOD						VARCHAR2(100),
    SEAT							VARCHAR2(10),
    SMOKING							VARCHAR2(10),
    TREAT_MENU						VARCHAR2(100),
    LCNS_NO							VARCHAR2(10),
	CREATED_TIME    				VARCHAR2(40), 
    MODIFIED_TIME  					VARCHAR2(40) 
 );   

COMMENT ON TABLE TOUR_DETAIL_INTRO_FOOD IS '음식점(contentTypeId=39) 소개 정보 테이블';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.CONTENT_ID IS '콘텐츠 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.CONTENT_TYPE_ID IS '관광타입 ID';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.CHK_CREDIT_CARD_FOOD IS '신용카드 가능 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.DISCOUNT_INFO_FOOD IS '할인정보';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.FIRST_MENU IS '대표 메뉴';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.INFO_CENTER_FOOD IS '문의 및 안내';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.KIDS_FACILITY IS '어린이 놀이방 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.OPEN_DATE_FOOD IS '개업일';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.OPEN_TIME_FOOD IS '영업시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.PACKING IS '포장 가능';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.PARKING_FOOD IS '주차시설';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.RESERVATION_FOOD IS '예약안내';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.REST_DATE_FOOD IS '쉬는 날';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.SCALE_FOOD IS '규모';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.SEAT IS '좌석수';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.SMOKING IS '금연/흡연 여부';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.TREAT_MENU IS '취급 메뉴';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.LCNS_NO IS '인허가번호';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.CREATED_TIME IS '레코드 생성 시간';
COMMENT ON COLUMN TOUR_DETAIL_INTRO_FOOD.MODIFIED_TIME IS '레코드 최종 수정 시간';


CREATE TABLE DETAIL_WITH_TOUR (
	CONTENT_ID VARCHAR2(100) PRIMARY KEY,
    PARKING VARCHAR2(1000),
    PUBLIC_TRANSPORT VARCHAR2(1000),
    ROUTE VARCHAR2(1000),
    TICKET_OFFICE VARCHAR2(1000),
    PROMOTION VARCHAR2(1000),
    WHEELCHAIR VARCHAR2(1000),
    EXIT VARCHAR2(1000),
    ELEVATOR VARCHAR2(1000),
    RESTROOM VARCHAR2(1000),
    AUDITORIUM VARCHAR2(1000),
    ROOM VARCHAR2(1000),
    HANDICAP_ETC VARCHAR2(1000),
    BRAILE_BLOCK VARCHAR2(1000),
    HELP_DOG VARCHAR2(1000),
    GUIDE_HUMAN VARCHAR2(1000),
    AUDIO_GUIDE VARCHAR2(1000),
    BIG_PRINT VARCHAR2(1000),
    BRAILE_PROMOTION VARCHAR2(1000),
    GUIDE_SYSTEM VARCHAR2(1000),
    BLIND_HANDICAP_ETC VARCHAR2(1000),
    SIGN_GUIDE VARCHAR2(1000),
    VIDEO_GUIDE VARCHAR2(1000),
    HEARING_ROOM VARCHAR2(1000),
    HEARING_HANDICAP_ETC VARCHAR2(1000),
    STROLLER VARCHAR2(1000),
    LACTATION_ROOM VARCHAR2(1000),
    BABY_SPARE_CHAIR VARCHAR2(1000),
    INFANTS_FAMILY_ETC VARCHAR2(1000)
);

COMMENT ON TABLE DETAIL_WITH_TOUR IS '무장애여행 상세정보 테이블';
COMMENT ON COLUMN DETAIL_WITH_TOUR.CONTENT_ID IS '콘텐츠 ID';
COMMENT ON COLUMN DETAIL_WITH_TOUR.PARKING IS '주차장 시설 여부 및 정보 (지체장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.PUBLIC_TRANSPORT IS '대중교통 정보 (지체장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.ROUTE IS '접근로 정보 (지체장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.TICKET_OFFICE IS '매표소 정보 (지체장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.PROMOTION IS '홍보물 정보 (지체장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.WHEELCHAIR IS '휠체어 정보 (지체장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.EXIT IS '출입구 정보 (지체장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.ELEVATOR IS '엘리베이터 정보 (지체장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.RESTROOM IS '화장실 정보 (지체장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.AUDITORIUM IS '관람석 정보 (지체장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.ROOM IS '객실 정보 (지체장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.HANDICAP_ETC IS '지체장애 기타 상세';
COMMENT ON COLUMN DETAIL_WITH_TOUR.BRAILE_BLOCK IS '점자블록 정보 (시각장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.HELP_DOG IS '보조견 동반가능 정보 (시각장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.GUIDE_HUMAN IS '안내요원 정보 (시각장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.AUDIO_GUIDE IS '오디오가이드 정보 (시각장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.BIG_PRINT IS '큰활자 홍보물 정보 (시각장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.BRAILE_PROMOTION IS '점자 홍보물 정보 (시각장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.GUIDE_SYSTEM IS '유도 시스템 정보 (시각장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.BLIND_HANDICAP_ETC IS '시각장애 기타 상세';
COMMENT ON COLUMN DETAIL_WITH_TOUR.SIGN_GUIDE IS '수화 안내판 정보 (청각장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.VIDEO_GUIDE IS '비디오가이드 정보 (청각장애)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.HEARING_ROOM IS '보조기기 제공 장소 정보 (청각장애) ';
COMMENT ON COLUMN DETAIL_WITH_TOUR.HEARING_HANDICAP_ETC IS '청각장애 기타상세';
COMMENT ON COLUMN DETAIL_WITH_TOUR.STROLLER IS '유모차 정보 (영유아가족)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.LACTATION_ROOM IS '수유실 정보 (영유아가족)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.BABY_SPARE_CHAIR IS '유아용 의자 정보 (영유아가족)';
COMMENT ON COLUMN DETAIL_WITH_TOUR.INFANTS_FAMILY_ETC IS '영유아가족 기타상세';

